-- 0PTICBOX Network upgrade: friends, reliable direct threads, blocking, and video messages.
-- Run this entire file once in the Supabase SQL Editor.

begin;

-- Base messaging tables are repeated here so this upgrade also repairs projects
-- where the earlier messaging section was never applied.
create table if not exists public.direct_threads (
  id uuid primary key default gen_random_uuid(),
  user_a uuid not null references public.profiles(id) on delete cascade,
  user_b uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint direct_threads_different_users check (user_a <> user_b),
  constraint direct_threads_canonical_order check (user_a::text < user_b::text),
  constraint direct_threads_unique_pair unique (user_a, user_b)
);

create table if not exists public.blocked_users (
  blocker_id uuid not null references public.profiles(id) on delete cascade,
  blocked_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (blocker_id, blocked_id),
  constraint blocked_users_different_users check (blocker_id <> blocked_id)
);

create table if not exists public.direct_messages (
  id bigint generated by default as identity primary key,
  thread_id uuid not null references public.direct_threads(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  body text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists direct_threads_user_a_idx on public.direct_threads (user_a, created_at desc);
create index if not exists direct_threads_user_b_idx on public.direct_threads (user_b, created_at desc);
create index if not exists direct_messages_thread_idx on public.direct_messages (thread_id, created_at);
create index if not exists blocked_users_blocked_idx on public.blocked_users (blocked_id, blocker_id);

alter table public.direct_threads enable row level security;
alter table public.direct_messages enable row level security;
alter table public.blocked_users enable row level security;

drop policy if exists "Members can read relevant block rows" on public.blocked_users;
create policy "Members can read relevant block rows"
on public.blocked_users for select
to authenticated
using ((select auth.uid()) in (blocker_id, blocked_id));

drop policy if exists "Members can create their own blocks" on public.blocked_users;
create policy "Members can create their own blocks"
on public.blocked_users for insert
to authenticated
with check (blocker_id = (select auth.uid()));

drop policy if exists "Members can remove their own blocks" on public.blocked_users;
create policy "Members can remove their own blocks"
on public.blocked_users for delete
to authenticated
using (blocker_id = (select auth.uid()));

-- =============================================================================
-- Friends
-- =============================================================================

create table if not exists public.friendships (
  id uuid primary key default gen_random_uuid(),
  requester_id uuid not null references public.profiles(id) on delete cascade,
  addressee_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint friendships_different_users check (requester_id <> addressee_id),
  constraint friendships_status_check check (status in ('pending', 'accepted'))
);

create unique index if not exists friendships_unique_pair_idx
on public.friendships (
  least(requester_id::text, addressee_id::text),
  greatest(requester_id::text, addressee_id::text)
);

create index if not exists friendships_requester_idx
on public.friendships (requester_id, status, updated_at desc);

create index if not exists friendships_addressee_idx
on public.friendships (addressee_id, status, updated_at desc);

alter table public.friendships enable row level security;

drop policy if exists "Members can read their friendships" on public.friendships;
create policy "Members can read their friendships"
on public.friendships for select
to authenticated
using (
  (select auth.uid()) in (requester_id, addressee_id)
  and not exists (
    select 1
    from public.blocked_users blocked
    where (blocked.blocker_id = requester_id and blocked.blocked_id = addressee_id)
       or (blocked.blocker_id = addressee_id and blocked.blocked_id = requester_id)
  )
);

grant select on public.friendships to authenticated;

-- Existing unblocked conversations become accepted friendships so the update
-- does not erase the people members were already messaging.
insert into public.friendships (requester_id, addressee_id, status, created_at, updated_at)
select thread.user_a, thread.user_b, 'accepted', thread.created_at, now()
from public.direct_threads thread
where not exists (
  select 1 from public.friendships friendship
  where (friendship.requester_id = thread.user_a and friendship.addressee_id = thread.user_b)
     or (friendship.requester_id = thread.user_b and friendship.addressee_id = thread.user_a)
)
and not exists (
  select 1 from public.blocked_users blocked
  where (blocked.blocker_id = thread.user_a and blocked.blocked_id = thread.user_b)
     or (blocked.blocker_id = thread.user_b and blocked.blocked_id = thread.user_a)
);

create or replace function public.are_friends(p_user_a uuid, p_user_b uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.friendships friendship
    where friendship.status = 'accepted'
      and (
        (friendship.requester_id = p_user_a and friendship.addressee_id = p_user_b)
        or
        (friendship.requester_id = p_user_b and friendship.addressee_id = p_user_a)
      )
  );
$$;

create or replace function public.send_friend_request(p_other_user uuid)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_me uuid := auth.uid();
  v_existing public.friendships%rowtype;
begin
  if v_me is null then
    raise exception 'Sign in required';
  end if;
  if p_other_user is null or p_other_user = v_me then
    raise exception 'Choose another member';
  end if;
  if not exists (select 1 from public.profiles where id = p_other_user) then
    raise exception 'Member not found';
  end if;
  if exists (
    select 1 from public.blocked_users blocked
    where (blocked.blocker_id = v_me and blocked.blocked_id = p_other_user)
       or (blocked.blocker_id = p_other_user and blocked.blocked_id = v_me)
  ) then
    raise exception 'Friend request unavailable';
  end if;

  select friendship.* into v_existing
  from public.friendships friendship
  where (friendship.requester_id = v_me and friendship.addressee_id = p_other_user)
     or (friendship.requester_id = p_other_user and friendship.addressee_id = v_me)
  limit 1;

  if found then
    if v_existing.status = 'accepted' then
      return 'accepted';
    end if;

    -- If the other member already requested the current user, accepting is
    -- automatic instead of creating a second reversed request.
    if v_existing.status = 'pending' and v_existing.addressee_id = v_me then
      update public.friendships
      set status = 'accepted', updated_at = now()
      where id = v_existing.id;
      return 'accepted';
    end if;

    return 'pending';
  end if;

  insert into public.friendships (requester_id, addressee_id, status)
  values (v_me, p_other_user, 'pending');
  return 'pending';
end;
$$;

create or replace function public.respond_friend_request(p_requester uuid, p_accept boolean)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_me uuid := auth.uid();
  v_id uuid;
begin
  if v_me is null then
    raise exception 'Sign in required';
  end if;

  select friendship.id into v_id
  from public.friendships friendship
  where friendship.requester_id = p_requester
    and friendship.addressee_id = v_me
    and friendship.status = 'pending'
  limit 1;

  if v_id is null then
    raise exception 'Friend request not found';
  end if;

  if coalesce(p_accept, false) then
    update public.friendships
    set status = 'accepted', updated_at = now()
    where id = v_id;
  else
    delete from public.friendships where id = v_id;
  end if;

  return true;
end;
$$;

create or replace function public.remove_friend(p_other_user uuid)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_me uuid := auth.uid();
begin
  if v_me is null then
    raise exception 'Sign in required';
  end if;

  delete from public.friendships friendship
  where (friendship.requester_id = v_me and friendship.addressee_id = p_other_user)
     or (friendship.requester_id = p_other_user and friendship.addressee_id = v_me);
  return true;
end;
$$;

create or replace function public.list_friends()
returns table (
  friend_id uuid,
  display_name text,
  avatar_url text,
  profile_status text,
  profile_tagline text,
  friends_since timestamptz
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    profile.id as friend_id,
    profile.display_name,
    profile.avatar_url,
    profile.status as profile_status,
    profile.profile_tagline,
    friendship.updated_at as friends_since
  from public.friendships friendship
  join public.profiles profile
    on profile.id = case
      when friendship.requester_id = auth.uid() then friendship.addressee_id
      else friendship.requester_id
    end
  where friendship.status = 'accepted'
    and auth.uid() in (friendship.requester_id, friendship.addressee_id)
    and not exists (
      select 1 from public.blocked_users blocked
      where (blocked.blocker_id = friendship.requester_id and blocked.blocked_id = friendship.addressee_id)
         or (blocked.blocker_id = friendship.addressee_id and blocked.blocked_id = friendship.requester_id)
    )
  order by lower(profile.display_name);
$$;

create or replace function public.list_friend_requests()
returns table (
  request_id uuid,
  direction text,
  other_user_id uuid,
  display_name text,
  avatar_url text,
  profile_status text,
  profile_tagline text,
  requested_at timestamptz
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    friendship.id as request_id,
    case when friendship.addressee_id = auth.uid() then 'incoming' else 'outgoing' end as direction,
    profile.id as other_user_id,
    profile.display_name,
    profile.avatar_url,
    profile.status as profile_status,
    profile.profile_tagline,
    friendship.created_at as requested_at
  from public.friendships friendship
  join public.profiles profile
    on profile.id = case
      when friendship.requester_id = auth.uid() then friendship.addressee_id
      else friendship.requester_id
    end
  where friendship.status = 'pending'
    and auth.uid() in (friendship.requester_id, friendship.addressee_id)
    and not exists (
      select 1 from public.blocked_users blocked
      where (blocked.blocker_id = friendship.requester_id and blocked.blocked_id = friendship.addressee_id)
         or (blocked.blocker_id = friendship.addressee_id and blocked.blocked_id = friendship.requester_id)
    )
  order by friendship.created_at desc;
$$;

revoke all on function public.are_friends(uuid, uuid) from public;
revoke all on function public.send_friend_request(uuid) from public;
revoke all on function public.respond_friend_request(uuid, boolean) from public;
revoke all on function public.remove_friend(uuid) from public;
revoke all on function public.list_friends() from public;
revoke all on function public.list_friend_requests() from public;
grant execute on function public.are_friends(uuid, uuid) to authenticated;
grant execute on function public.send_friend_request(uuid) to authenticated;
grant execute on function public.respond_friend_request(uuid, boolean) to authenticated;
grant execute on function public.remove_friend(uuid) to authenticated;
grant execute on function public.list_friends() to authenticated;
grant execute on function public.list_friend_requests() to authenticated;

-- =============================================================================
-- Blocking
-- =============================================================================

create or replace function public.block_member(p_other_user uuid)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_me uuid := auth.uid();
begin
  if v_me is null then
    raise exception 'Sign in required';
  end if;
  if p_other_user is null or p_other_user = v_me then
    raise exception 'Choose another member';
  end if;

  insert into public.blocked_users (blocker_id, blocked_id)
  values (v_me, p_other_user)
  on conflict (blocker_id, blocked_id) do nothing;

  delete from public.friendships friendship
  where (friendship.requester_id = v_me and friendship.addressee_id = p_other_user)
     or (friendship.requester_id = p_other_user and friendship.addressee_id = v_me);

  return true;
end;
$$;

create or replace function public.unblock_member(p_other_user uuid)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_me uuid := auth.uid();
begin
  if v_me is null then
    raise exception 'Sign in required';
  end if;
  delete from public.blocked_users
  where blocker_id = v_me and blocked_id = p_other_user;
  return true;
end;
$$;

revoke all on function public.block_member(uuid) from public;
revoke all on function public.unblock_member(uuid) from public;
grant execute on function public.block_member(uuid) to authenticated;
grant execute on function public.unblock_member(uuid) to authenticated;

-- =============================================================================
-- Friend-only, block-aware direct threads
-- =============================================================================

create or replace function public.can_view_direct_thread(p_thread uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.direct_threads thread
    where thread.id = p_thread
      and auth.uid() in (thread.user_a, thread.user_b)
      and public.are_friends(thread.user_a, thread.user_b)
      and not exists (
        select 1 from public.blocked_users blocked
        where (blocked.blocker_id = thread.user_a and blocked.blocked_id = thread.user_b)
           or (blocked.blocker_id = thread.user_b and blocked.blocked_id = thread.user_a)
      )
  );
$$;

create or replace function public.can_send_direct_message(p_thread uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select public.can_view_direct_thread(p_thread);
$$;

-- Drop and recreate this RPC so PostgREST sees the exact input parameter name
-- used by the browser: p_other_user.
drop function if exists public.start_direct_thread(uuid);
create function public.start_direct_thread(p_other_user uuid)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_me uuid := auth.uid();
  v_a uuid;
  v_b uuid;
  v_thread uuid;
begin
  if v_me is null then
    raise exception 'Sign in required';
  end if;
  if p_other_user is null or p_other_user = v_me then
    raise exception 'Choose another member';
  end if;
  if not public.are_friends(v_me, p_other_user) then
    raise exception 'Only accepted friends can start a conversation';
  end if;
  if exists (
    select 1 from public.blocked_users blocked
    where (blocked.blocker_id = v_me and blocked.blocked_id = p_other_user)
       or (blocked.blocker_id = p_other_user and blocked.blocked_id = v_me)
  ) then
    raise exception 'Conversation unavailable';
  end if;

  if v_me::text < p_other_user::text then
    v_a := v_me;
    v_b := p_other_user;
  else
    v_a := p_other_user;
    v_b := v_me;
  end if;

  select thread.id into v_thread
  from public.direct_threads thread
  where thread.user_a = v_a and thread.user_b = v_b;

  if v_thread is null then
    insert into public.direct_threads (user_a, user_b)
    values (v_a, v_b)
    returning id into v_thread;
  end if;

  return v_thread;
end;
$$;

revoke all on function public.can_view_direct_thread(uuid) from public;
revoke all on function public.can_send_direct_message(uuid) from public;
revoke all on function public.start_direct_thread(uuid) from public;
grant execute on function public.can_view_direct_thread(uuid) to authenticated;
grant execute on function public.can_send_direct_message(uuid) to authenticated;
grant execute on function public.start_direct_thread(uuid) to authenticated;

drop policy if exists "Members can read their direct threads" on public.direct_threads;
create policy "Members can read their direct threads"
on public.direct_threads for select
to authenticated
using (public.can_view_direct_thread(id));

drop policy if exists "Members can read their direct messages" on public.direct_messages;
create policy "Members can read their direct messages"
on public.direct_messages for select
to authenticated
using (public.can_view_direct_thread(thread_id));

drop policy if exists "Members can send direct messages" on public.direct_messages;
create policy "Members can send direct messages"
on public.direct_messages for insert
to authenticated
with check (
  sender_id = (select auth.uid())
  and public.can_send_direct_message(thread_id)
);

-- =============================================================================
-- Video message fields
-- =============================================================================

alter table public.direct_messages
  add column if not exists message_type text not null default 'text';
alter table public.direct_messages
  add column if not exists media_path text not null default '';
alter table public.direct_messages
  add column if not exists media_name text not null default '';
alter table public.direct_messages
  add column if not exists media_size bigint not null default 0;
alter table public.direct_messages
  alter column body set default '';

alter table public.direct_messages
  drop constraint if exists direct_messages_body_check;
alter table public.direct_messages
  drop constraint if exists direct_messages_content_check;
alter table public.direct_messages
  drop constraint if exists direct_messages_message_type_check;
alter table public.direct_messages
  drop constraint if exists direct_messages_media_name_check;

alter table public.direct_messages
  add constraint direct_messages_message_type_check
  check (message_type in ('text', 'video'));

alter table public.direct_messages
  add constraint direct_messages_media_name_check
  check (char_length(media_name) <= 180);

alter table public.direct_messages
  add constraint direct_messages_content_check
  check (
    (
      message_type = 'text'
      and char_length(trim(body)) between 1 and 1000
      and media_path = ''
      and media_size = 0
    )
    or
    (
      message_type = 'video'
      and char_length(body) <= 1000
      and char_length(media_path) between 1 and 2048
      and media_size between 1 and 52428800
    )
  );

-- Private bucket. Files use: <thread UUID>/<sender UUID>/<random filename>
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'message-media',
  'message-media',
  false,
  52428800,
  array['video/mp4','video/webm','video/quicktime']
)
on conflict (id) do update
set public = false,
    file_size_limit = 52428800,
    allowed_mime_types = excluded.allowed_mime_types;

create or replace function public.message_media_can_read(p_name text)
returns boolean
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_parts text[];
  v_thread uuid;
begin
  v_parts := string_to_array(coalesce(p_name, ''), '/');
  if array_length(v_parts, 1) < 3 then return false; end if;
  begin
    v_thread := v_parts[1]::uuid;
  exception when invalid_text_representation then
    return false;
  end;
  return public.can_view_direct_thread(v_thread);
end;
$$;

create or replace function public.message_media_can_write(p_name text)
returns boolean
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_parts text[];
  v_thread uuid;
begin
  v_parts := string_to_array(coalesce(p_name, ''), '/');
  if array_length(v_parts, 1) < 3 then return false; end if;
  if v_parts[2] <> auth.uid()::text then return false; end if;
  begin
    v_thread := v_parts[1]::uuid;
  exception when invalid_text_representation then
    return false;
  end;
  return public.can_send_direct_message(v_thread);
end;
$$;

revoke all on function public.message_media_can_read(text) from public;
revoke all on function public.message_media_can_write(text) from public;
grant execute on function public.message_media_can_read(text) to authenticated;
grant execute on function public.message_media_can_write(text) to authenticated;

drop policy if exists "Thread members can view private message media" on storage.objects;
create policy "Thread members can view private message media"
on storage.objects for select
to authenticated
using (
  bucket_id = 'message-media'
  and public.message_media_can_read(name)
);

drop policy if exists "Thread members can upload private message media" on storage.objects;
create policy "Thread members can upload private message media"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'message-media'
  and public.message_media_can_write(name)
);

drop policy if exists "Senders can delete private message media" on storage.objects;
create policy "Senders can delete private message media"
on storage.objects for delete
to authenticated
using (
  bucket_id = 'message-media'
  and (storage.foldername(name))[2] = (select auth.uid())::text
  and public.message_media_can_read(name)
);

-- Table grants remain controlled by RLS.
grant select on public.direct_threads to authenticated;
grant select, insert on public.direct_messages to authenticated;
grant select, insert, delete on public.blocked_users to authenticated;
grant usage, select on sequence public.direct_messages_id_seq to authenticated;

-- Ensure direct-message changes are available to realtime listeners.
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'direct_messages'
  ) then
    alter publication supabase_realtime add table public.direct_messages;
  end if;
end $$;

-- Force the Data API to discover the recreated RPC and added columns now.
notify pgrst, 'reload schema';

commit;
