-- 0PTICBOX static-site CMS + member reviews schema for Supabase.
-- Run this entire file in the Supabase SQL Editor.
-- It is safe to run again when updating an existing 0PTICBOX setup.

create table if not exists public.site_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.community_posts (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 1 and 120),
  body text not null check (char_length(body) between 1 and 5000),
  image_url text,
  published boolean not null default false,
  published_at timestamptz,
  author_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.site_content (
  key text primary key,
  value text not null default '',
  updated_at timestamptz not null default now()
);

-- Public member profile. Only the display name is exposed to site visitors.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null check (char_length(display_name) between 2 and 32),
  bio text not null default '' check (char_length(bio) <= 600),
  status text not null default '' check (char_length(status) <= 80),
  avatar_url text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles add column if not exists bio text not null default '';
alter table public.profiles add column if not exists status text not null default '';
alter table public.profiles add column if not exists avatar_url text not null default '';

create table if not exists public.product_reviews (
  id bigint generated by default as identity primary key,
  product_slug text not null check (product_slug in (
    'opticscope',
    '0ps3',
    'spectravault',
    'distortion',
    'dj-visual-studio',
    'boxed-arp',
    'orbital-repair',
    'inner-light-runner'
  )),
  user_id uuid not null references public.profiles(id) on delete cascade,
  rating smallint not null check (rating between 1 and 5),
  comment text not null check (char_length(comment) between 1 and 500),
  visible boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, product_slug)
);

create index if not exists product_reviews_product_slug_idx
  on public.product_reviews (product_slug, visible, updated_at desc);

alter table public.site_admins enable row level security;
alter table public.community_posts enable row level security;
alter table public.site_content enable row level security;
alter table public.profiles enable row level security;
alter table public.product_reviews enable row level security;

create or replace function public.is_site_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.site_admins
    where user_id = (select auth.uid())
  );
$$;

revoke all on function public.is_site_admin() from public;
grant execute on function public.is_site_admin() to anon, authenticated;

-- Automatically create the public display-name row for each new Auth account.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  requested_name text;
  fallback_name text;
begin
  requested_name := nullif(trim(new.raw_user_meta_data ->> 'display_name'), '');
  if requested_name is not null and char_length(requested_name) not between 2 and 32 then
    requested_name := null;
  end if;

  fallback_name := nullif(split_part(new.email, '@', 1), '');
  if fallback_name is null or char_length(fallback_name) < 2 then
    fallback_name := 'Member';
  end if;

  insert into public.profiles (id, display_name)
  values (
    new.id,
    left(coalesce(requested_name, fallback_name), 32)
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

revoke all on function public.handle_new_user() from public;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Backfill profiles for accounts that existed before this update.
insert into public.profiles (id, display_name)
select
  id,
  case
    when char_length(coalesce(
      nullif(trim(raw_user_meta_data ->> 'display_name'), ''),
      nullif(split_part(email, '@', 1), ''),
      'Member'
    )) >= 2
    then left(coalesce(
      nullif(trim(raw_user_meta_data ->> 'display_name'), ''),
      nullif(split_part(email, '@', 1), ''),
      'Member'
    ), 32)
    else 'Member'
  end
from auth.users
on conflict (id) do nothing;

-- Admin allowlist policies.
drop policy if exists "Admins can read their admin record" on public.site_admins;
create policy "Admins can read their admin record"
on public.site_admins for select
to authenticated
using (user_id = (select auth.uid()));

-- Community posts policies.
drop policy if exists "Public can read published posts" on public.community_posts;
create policy "Public can read published posts"
on public.community_posts for select
to anon, authenticated
using (published = true or public.is_site_admin());

drop policy if exists "Admins can insert posts" on public.community_posts;
create policy "Admins can insert posts"
on public.community_posts for insert
to authenticated
with check (public.is_site_admin());

drop policy if exists "Admins can update posts" on public.community_posts;
create policy "Admins can update posts"
on public.community_posts for update
to authenticated
using (public.is_site_admin())
with check (public.is_site_admin());

drop policy if exists "Admins can delete posts" on public.community_posts;
create policy "Admins can delete posts"
on public.community_posts for delete
to authenticated
using (public.is_site_admin());

-- Editable site text policies.
drop policy if exists "Public can read site content" on public.site_content;
create policy "Public can read site content"
on public.site_content for select
to anon, authenticated
using (true);

drop policy if exists "Admins can insert site content" on public.site_content;
create policy "Admins can insert site content"
on public.site_content for insert
to authenticated
with check (public.is_site_admin());

drop policy if exists "Admins can update site content" on public.site_content;
create policy "Admins can update site content"
on public.site_content for update
to authenticated
using (public.is_site_admin())
with check (public.is_site_admin());

drop policy if exists "Admins can delete site content" on public.site_content;
create policy "Admins can delete site content"
on public.site_content for delete
to authenticated
using (public.is_site_admin());

-- Member profile policies.
drop policy if exists "Public can read member display names" on public.profiles;
create policy "Public can read member display names"
on public.profiles for select
to anon, authenticated
using (true);

drop policy if exists "Members can create their own profile" on public.profiles;
create policy "Members can create their own profile"
on public.profiles for insert
to authenticated
with check (id = (select auth.uid()));

drop policy if exists "Members can update their own profile" on public.profiles;
create policy "Members can update their own profile"
on public.profiles for update
to authenticated
using (id = (select auth.uid()))
with check (id = (select auth.uid()));

-- Review policies. Anyone can read visible reviews. Members can maintain one
-- visible review per product. Admins can hide, restore, or delete any review.
drop policy if exists "Public can read visible product reviews" on public.product_reviews;
create policy "Public can read visible product reviews"
on public.product_reviews for select
to anon, authenticated
using (
  visible = true
  or user_id = (select auth.uid())
  or public.is_site_admin()
);

drop policy if exists "Members can create their own visible reviews" on public.product_reviews;
create policy "Members can create their own visible reviews"
on public.product_reviews for insert
to authenticated
with check (
  user_id = (select auth.uid())
  and visible = true
);

drop policy if exists "Members can update their own visible reviews" on public.product_reviews;
create policy "Members can update their own visible reviews"
on public.product_reviews for update
to authenticated
using (
  (user_id = (select auth.uid()) and visible = true)
  or public.is_site_admin()
)
with check (
  (user_id = (select auth.uid()) and visible = true)
  or public.is_site_admin()
);

drop policy if exists "Members or admins can delete reviews" on public.product_reviews;
create policy "Members or admins can delete reviews"
on public.product_reviews for delete
to authenticated
using (
  user_id = (select auth.uid())
  or public.is_site_admin()
);

-- Public profile-picture bucket. Members can only write inside their own folder.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('profile-images', 'profile-images', true, 5242880, array['image/png','image/jpeg','image/webp','image/gif'])
on conflict (id) do update set public = true, file_size_limit = 5242880, allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public can view profile pictures" on storage.objects;
create policy "Public can view profile pictures" on storage.objects for select to public using (bucket_id = 'profile-images');

drop policy if exists "Members can upload their profile picture" on storage.objects;
create policy "Members can upload their profile picture" on storage.objects for insert to authenticated
with check (bucket_id = 'profile-images' and (storage.foldername(name))[1] = (select auth.uid())::text);

drop policy if exists "Members can update their profile picture" on storage.objects;
create policy "Members can update their profile picture" on storage.objects for update to authenticated
using (bucket_id = 'profile-images' and (storage.foldername(name))[1] = (select auth.uid())::text)
with check (bucket_id = 'profile-images' and (storage.foldername(name))[1] = (select auth.uid())::text);

drop policy if exists "Members can delete their profile picture" on storage.objects;
create policy "Members can delete their profile picture" on storage.objects for delete to authenticated
using (bucket_id = 'profile-images' and (storage.foldername(name))[1] = (select auth.uid())::text);

-- Data API grants. RLS still decides which rows each visitor can use.
grant select on public.site_admins to authenticated;
grant select on public.community_posts to anon, authenticated;
grant insert, update, delete on public.community_posts to authenticated;
grant select on public.site_content to anon, authenticated;
grant insert, update, delete on public.site_content to authenticated;
grant select on public.profiles to anon, authenticated;
grant insert, update on public.profiles to authenticated;
grant select on public.product_reviews to anon, authenticated;
grant insert, update, delete on public.product_reviews to authenticated;
grant usage, select on sequence public.community_posts_id_seq to authenticated;
grant usage, select on sequence public.product_reviews_id_seq to authenticated;

insert into public.site_content (key, value) values
  ('profile_status', 'Things are getting W€!RD'),
  ('profile_bio', 'Electronic music, live visuals, browser experiments, and tiny games.'),
  ('featured_title', '0PTICSCOPE'),
  ('featured_description', 'Turn audio, images, and generated signals into live motion. The landing page stays lightweight—the full visualizer only opens when you launch it.'),
  ('site_status', 'making electronic music, strange visuals, and software that looks like it crawled out of a CRT at 2:00 AM.')
on conflict (key) do nothing;
-- ==========================================================================
-- Member activity feed: Listening Now + Going to an Event
-- ==========================================================================

create table if not exists public.activity_posts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  post_type text not null check (post_type in ('listening', 'event')),
  title text not null check (char_length(title) between 1 and 160),
  subtitle text not null default '' check (char_length(subtitle) <= 100),
  caption text not null default '' check (char_length(caption) <= 500),
  media_url text not null default '' check (char_length(media_url) <= 2048),
  image_url text not null default '' check (char_length(image_url) <= 2048),
  event_date date,
  city text not null default '' check (char_length(city) <= 100),
  visible boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    (post_type = 'listening' and char_length(subtitle) between 1 and 100)
    or
    (post_type = 'event' and event_date is not null and char_length(city) between 1 and 100)
  )
);

create index if not exists activity_posts_public_feed_idx
  on public.activity_posts (visible, created_at desc);

create index if not exists activity_posts_user_idx
  on public.activity_posts (user_id, visible, created_at desc);

alter table public.activity_posts enable row level security;

drop policy if exists "Public can read visible activity posts" on public.activity_posts;
create policy "Public can read visible activity posts"
on public.activity_posts for select
to anon, authenticated
using (
  visible = true
  or user_id = (select auth.uid())
  or public.is_site_admin()
);

drop policy if exists "Members can create their own activity posts" on public.activity_posts;
create policy "Members can create their own activity posts"
on public.activity_posts for insert
to authenticated
with check (
  user_id = (select auth.uid())
  and visible = true
);

drop policy if exists "Members or admins can update activity posts" on public.activity_posts;
create policy "Members or admins can update activity posts"
on public.activity_posts for update
to authenticated
using (
  (user_id = (select auth.uid()) and visible = true)
  or public.is_site_admin()
)
with check (
  (user_id = (select auth.uid()) and visible = true)
  or public.is_site_admin()
);

drop policy if exists "Members or admins can delete activity posts" on public.activity_posts;
create policy "Members or admins can delete activity posts"
on public.activity_posts for delete
to authenticated
using (
  user_id = (select auth.uid())
  or public.is_site_admin()
);

grant select on public.activity_posts to anon, authenticated;
grant insert, update, delete on public.activity_posts to authenticated;
grant usage, select on sequence public.activity_posts_id_seq to authenticated;

-- Public image bucket for album art and event flyers.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'community-media',
  'community-media',
  true,
  5242880,
  array['image/png','image/jpeg','image/webp','image/gif']
)
on conflict (id) do update
set public = true,
    file_size_limit = 5242880,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public can view community media" on storage.objects;
create policy "Public can view community media"
on storage.objects for select
to public
using (bucket_id = 'community-media');

drop policy if exists "Members can upload their community media" on storage.objects;
create policy "Members can upload their community media"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'community-media'
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

drop policy if exists "Members can update their community media" on storage.objects;
create policy "Members can update their community media"
on storage.objects for update
to authenticated
using (
  bucket_id = 'community-media'
  and (storage.foldername(name))[1] = (select auth.uid())::text
)
with check (
  bucket_id = 'community-media'
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

drop policy if exists "Members can delete their community media" on storage.objects;
create policy "Members can delete their community media"
on storage.objects for delete
to authenticated
using (
  bucket_id = 'community-media'
  and (storage.foldername(name))[1] = (select auth.uid())::text
);
-- ==========================================================================
-- Personalized public profiles
-- ==========================================================================

alter table public.profiles
  add column if not exists background_url text not null default '';

alter table public.profiles
  add column if not exists background_dim smallint not null default 62;

alter table public.profiles
  add column if not exists accent_color text not null default '#ff6b36';

alter table public.profiles
  add column if not exists profile_tagline text not null default '';

alter table public.profiles
  add column if not exists instagram_url text not null default '';

alter table public.profiles
  add column if not exists youtube_url text not null default '';

alter table public.profiles
  drop constraint if exists profiles_background_dim_check;

alter table public.profiles
  add constraint profiles_background_dim_check
  check (background_dim between 20 and 90);

alter table public.profiles
  drop constraint if exists profiles_accent_color_check;

alter table public.profiles
  add constraint profiles_accent_color_check
  check (accent_color ~ '^#[0-9A-Fa-f]{6}$');

alter table public.profiles
  drop constraint if exists profiles_profile_tagline_check;

alter table public.profiles
  add constraint profiles_profile_tagline_check
  check (char_length(profile_tagline) <= 120);

alter table public.profiles
  drop constraint if exists profiles_instagram_url_check;

alter table public.profiles
  add constraint profiles_instagram_url_check
  check (char_length(instagram_url) <= 2048);

alter table public.profiles
  drop constraint if exists profiles_youtube_url_check;

alter table public.profiles
  add constraint profiles_youtube_url_check
  check (char_length(youtube_url) <= 2048);

-- Raise the public profile-media limit so animated backgrounds can be used.
update storage.buckets
set file_size_limit = 8388608,
    allowed_mime_types = array['image/png','image/jpeg','image/webp','image/gif']
where id = 'profile-images';

-- =============================================================================
-- Regular community posts
-- =============================================================================

alter table public.activity_posts
  alter column title set default '';

alter table public.activity_posts
  drop constraint if exists activity_posts_post_type_check;
alter table public.activity_posts
  drop constraint if exists activity_posts_title_check;
alter table public.activity_posts
  drop constraint if exists activity_posts_caption_check;
alter table public.activity_posts
  drop constraint if exists activity_posts_check;
alter table public.activity_posts
  drop constraint if exists activity_posts_content_check;

alter table public.activity_posts
  add constraint activity_posts_post_type_check
  check (post_type in ('post', 'listening', 'event'));

alter table public.activity_posts
  add constraint activity_posts_title_check
  check (char_length(title) <= 160);

alter table public.activity_posts
  add constraint activity_posts_caption_check
  check (char_length(caption) <= 2000);

alter table public.activity_posts
  add constraint activity_posts_content_check
  check (
    (
      post_type = 'post'
      and (
        char_length(trim(caption)) between 1 and 2000
        or char_length(trim(image_url)) between 1 and 2048
      )
    )
    or
    (
      post_type = 'listening'
      and char_length(trim(title)) between 1 and 160
      and char_length(trim(subtitle)) between 1 and 100
    )
    or
    (
      post_type = 'event'
      and char_length(trim(title)) between 1 and 160
      and event_date is not null
      and char_length(trim(city)) between 1 and 100
    )
  );

-- =============================================================================
-- Private member-to-member messaging
-- =============================================================================

create table if not exists public.direct_threads (
  id uuid primary key default gen_random_uuid(),
  user_a uuid not null references public.profiles(id) on delete cascade,
  user_b uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint direct_threads_different_users check (user_a <> user_b),
  constraint direct_threads_canonical_order check (user_a::text < user_b::text),
  constraint direct_threads_unique_pair unique (user_a, user_b)
);

create table if not exists public.blocked_users (
  blocker_id uuid not null references public.profiles(id) on delete cascade,
  blocked_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (blocker_id, blocked_id),
  constraint blocked_users_different_users check (blocker_id <> blocked_id)
);

create table if not exists public.direct_messages (
  id bigint generated by default as identity primary key,
  thread_id uuid not null references public.direct_threads(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now(),
  constraint direct_messages_body_check check (char_length(trim(body)) between 1 and 1000)
);

create index if not exists direct_threads_user_a_idx on public.direct_threads (user_a, created_at desc);
create index if not exists direct_threads_user_b_idx on public.direct_threads (user_b, created_at desc);
create index if not exists direct_messages_thread_idx on public.direct_messages (thread_id, created_at);
create index if not exists blocked_users_blocked_idx on public.blocked_users (blocked_id, blocker_id);

alter table public.direct_threads enable row level security;
alter table public.direct_messages enable row level security;
alter table public.blocked_users enable row level security;

drop policy if exists "Members can read their direct threads" on public.direct_threads;
create policy "Members can read their direct threads"
on public.direct_threads for select to authenticated
using ((select auth.uid()) in (user_a, user_b));

drop policy if exists "Members can read their direct messages" on public.direct_messages;
create policy "Members can read their direct messages"
on public.direct_messages for select to authenticated
using (
  exists (
    select 1 from public.direct_threads thread
    where thread.id = direct_messages.thread_id
      and (select auth.uid()) in (thread.user_a, thread.user_b)
  )
);

drop policy if exists "Members can read relevant block rows" on public.blocked_users;
create policy "Members can read relevant block rows"
on public.blocked_users for select to authenticated
using ((select auth.uid()) in (blocker_id, blocked_id));

drop policy if exists "Members can create their own blocks" on public.blocked_users;
create policy "Members can create their own blocks"
on public.blocked_users for insert to authenticated
with check (blocker_id = (select auth.uid()));

drop policy if exists "Members can remove their own blocks" on public.blocked_users;
create policy "Members can remove their own blocks"
on public.blocked_users for delete to authenticated
using (blocker_id = (select auth.uid()));

create or replace function public.start_direct_thread(p_other_user uuid)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_me uuid := auth.uid();
  v_a uuid;
  v_b uuid;
  v_thread uuid;
begin
  if v_me is null then
    raise exception 'Sign in required';
  end if;
  if p_other_user is null or p_other_user = v_me then
    raise exception 'Choose another member';
  end if;
  if not exists (select 1 from public.profiles where id = p_other_user) then
    raise exception 'Member not found';
  end if;
  if exists (
    select 1 from public.blocked_users
    where (blocker_id = v_me and blocked_id = p_other_user)
       or (blocker_id = p_other_user and blocked_id = v_me)
  ) then
    raise exception 'Conversation unavailable';
  end if;
  if v_me::text < p_other_user::text then v_a := v_me; v_b := p_other_user;
  else v_a := p_other_user; v_b := v_me; end if;
  select id into v_thread from public.direct_threads where user_a = v_a and user_b = v_b;
  if v_thread is null then
    insert into public.direct_threads (user_a, user_b) values (v_a, v_b) returning id into v_thread;
  end if;
  return v_thread;
end;
$$;

create or replace function public.can_send_direct_message(p_thread uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.direct_threads thread
    where thread.id = p_thread
      and auth.uid() in (thread.user_a, thread.user_b)
      and not exists (
        select 1 from public.blocked_users blocked
        where (blocked.blocker_id = thread.user_a and blocked.blocked_id = thread.user_b)
           or (blocked.blocker_id = thread.user_b and blocked.blocked_id = thread.user_a)
      )
  );
$$;

revoke all on function public.start_direct_thread(uuid) from public;
revoke all on function public.can_send_direct_message(uuid) from public;
grant execute on function public.start_direct_thread(uuid) to authenticated;
grant execute on function public.can_send_direct_message(uuid) to authenticated;

drop policy if exists "Members can send direct messages" on public.direct_messages;
create policy "Members can send direct messages"
on public.direct_messages for insert to authenticated
with check (
  sender_id = (select auth.uid())
  and public.can_send_direct_message(thread_id)
);

grant select on public.direct_threads to authenticated;
grant select, insert on public.direct_messages to authenticated;
grant select, insert, delete on public.blocked_users to authenticated;
grant usage, select on sequence public.direct_messages_id_seq to authenticated;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'direct_messages'
  ) then
    alter publication supabase_realtime add table public.direct_messages;
  end if;
end $$;

notify pgrst, 'reload schema';
-- ===== 2026-08 FRIENDS + VIDEO MESSAGING UPGRADE =====
-- 0PTICBOX messaging upgrade: friends, video attachments, block cleanup, and RPC repair.
-- Run this entire file once in Supabase SQL Editor, then refresh the website.

create table if not exists public.friendships (
  id uuid primary key default gen_random_uuid(),
  user_a uuid not null references public.profiles(id) on delete cascade,
  user_b uuid not null references public.profiles(id) on delete cascade,
  requested_by uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending','accepted','declined')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint friendships_different_users check (user_a <> user_b),
  constraint friendships_canonical_order check (user_a::text < user_b::text),
  constraint friendships_requester_is_member check (requested_by in (user_a, user_b)),
  constraint friendships_unique_pair unique (user_a, user_b)
);
create index if not exists friendships_user_a_idx on public.friendships (user_a, status, updated_at desc);
create index if not exists friendships_user_b_idx on public.friendships (user_b, status, updated_at desc);
alter table public.friendships enable row level security;
drop policy if exists "Members can read their friendships" on public.friendships;
create policy "Members can read their friendships" on public.friendships for select to authenticated using ((select auth.uid()) in (user_a, user_b));
grant select on public.friendships to authenticated;

create or replace function public.send_friend_request(p_other_user uuid)
returns uuid language plpgsql security definer set search_path = public as $$
declare v_me uuid := auth.uid(); v_a uuid; v_b uuid; v_id uuid; v_existing public.friendships%rowtype;
begin
  if v_me is null then raise exception 'Sign in required'; end if;
  if p_other_user is null or p_other_user = v_me then raise exception 'Choose another member'; end if;
  if not exists (select 1 from public.profiles where id = p_other_user) then raise exception 'Member not found'; end if;
  if exists (select 1 from public.blocked_users where (blocker_id=v_me and blocked_id=p_other_user) or (blocker_id=p_other_user and blocked_id=v_me)) then raise exception 'Friend request unavailable'; end if;
  if v_me::text < p_other_user::text then v_a:=v_me; v_b:=p_other_user; else v_a:=p_other_user; v_b:=v_me; end if;
  select * into v_existing from public.friendships where user_a=v_a and user_b=v_b;
  if found then
    if v_existing.status='accepted' then return v_existing.id; end if;
    if v_existing.status='pending' and v_existing.requested_by<>v_me then update public.friendships set status='accepted', updated_at=now() where id=v_existing.id returning id into v_id; return v_id; end if;
    update public.friendships set requested_by=v_me, status='pending', updated_at=now() where id=v_existing.id returning id into v_id; return v_id;
  end if;
  insert into public.friendships(user_a,user_b,requested_by) values(v_a,v_b,v_me) returning id into v_id; return v_id;
end $$;

create or replace function public.respond_friend_request(p_friendship uuid, p_accept boolean)
returns boolean language plpgsql security definer set search_path = public as $$
declare v_me uuid := auth.uid(); v_row public.friendships%rowtype;
begin
  if v_me is null then raise exception 'Sign in required'; end if;
  select * into v_row from public.friendships where id=p_friendship and v_me in (user_a,user_b) and status='pending';
  if not found then raise exception 'Friend request not found'; end if;
  if v_row.requested_by=v_me then raise exception 'Only the recipient can answer this request'; end if;
  update public.friendships set status=case when p_accept then 'accepted' else 'declined' end, updated_at=now() where id=p_friendship;
  return true;
end $$;

create or replace function public.remove_friend(p_other_user uuid)
returns boolean language plpgsql security definer set search_path = public as $$
declare v_me uuid := auth.uid();
begin
  if v_me is null then raise exception 'Sign in required'; end if;
  delete from public.friendships where (user_a=v_me and user_b=p_other_user) or (user_a=p_other_user and user_b=v_me);
  return true;
end $$;

revoke all on function public.send_friend_request(uuid) from public;
revoke all on function public.respond_friend_request(uuid,boolean) from public;
revoke all on function public.remove_friend(uuid) from public;
grant execute on function public.send_friend_request(uuid) to authenticated;
grant execute on function public.respond_friend_request(uuid,boolean) to authenticated;
grant execute on function public.remove_friend(uuid) to authenticated;

alter table public.direct_messages add column if not exists media_path text not null default '';
alter table public.direct_messages add column if not exists media_type text not null default '';
alter table public.direct_messages add column if not exists media_name text not null default '';
alter table public.direct_messages add column if not exists media_size bigint not null default 0;
alter table public.direct_messages alter column body set default '';
alter table public.direct_messages drop constraint if exists direct_messages_body_check;
alter table public.direct_messages add constraint direct_messages_body_or_media_check check (
  char_length(body) <= 1000
  and (char_length(trim(body)) >= 1 or char_length(trim(media_path)) >= 1)
  and media_size between 0 and 52428800
);

create or replace function public.are_friends(p_one uuid, p_two uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists(select 1 from public.friendships where status='accepted' and ((user_a=p_one and user_b=p_two) or (user_a=p_two and user_b=p_one)));
$$;
revoke all on function public.are_friends(uuid,uuid) from public;
grant execute on function public.are_friends(uuid,uuid) to authenticated;

create or replace function public.start_direct_thread(p_other_user uuid)
returns uuid language plpgsql security definer set search_path = public as $$
declare v_me uuid := auth.uid(); v_a uuid; v_b uuid; v_thread uuid;
begin
  if v_me is null then raise exception 'Sign in required'; end if;
  if p_other_user is null or p_other_user=v_me then raise exception 'Choose another member'; end if;
  if not public.are_friends(v_me,p_other_user) then raise exception 'Only accepted friends can be messaged'; end if;
  if exists(select 1 from public.blocked_users where (blocker_id=v_me and blocked_id=p_other_user) or (blocker_id=p_other_user and blocked_id=v_me)) then raise exception 'Conversation unavailable'; end if;
  if v_me::text<p_other_user::text then v_a:=v_me; v_b:=p_other_user; else v_a:=p_other_user; v_b:=v_me; end if;
  select id into v_thread from public.direct_threads where user_a=v_a and user_b=v_b;
  if v_thread is null then insert into public.direct_threads(user_a,user_b) values(v_a,v_b) returning id into v_thread; end if;
  return v_thread;
end $$;

create or replace function public.can_send_direct_message(p_thread uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists(
    select 1 from public.direct_threads t
    where t.id=p_thread and auth.uid() in (t.user_a,t.user_b)
      and public.are_friends(t.user_a,t.user_b)
      and not exists(select 1 from public.blocked_users b where (b.blocker_id=t.user_a and b.blocked_id=t.user_b) or (b.blocker_id=t.user_b and b.blocked_id=t.user_a))
  );
$$;
revoke all on function public.start_direct_thread(uuid) from public;
revoke all on function public.can_send_direct_message(uuid) from public;
grant execute on function public.start_direct_thread(uuid) to authenticated;
grant execute on function public.can_send_direct_message(uuid) to authenticated;

-- Hide blocked or unfriended conversations at the database level.
drop policy if exists "Members can read their direct threads" on public.direct_threads;
create policy "Members can read their direct threads" on public.direct_threads for select to authenticated using (
  (select auth.uid()) in (user_a,user_b)
  and public.are_friends(user_a,user_b)
  and not exists(select 1 from public.blocked_users b where (b.blocker_id=user_a and b.blocked_id=user_b) or (b.blocker_id=user_b and b.blocked_id=user_a))
);
drop policy if exists "Members can read their direct messages" on public.direct_messages;
create policy "Members can read their direct messages" on public.direct_messages for select to authenticated using (
  exists(select 1 from public.direct_threads t where t.id=direct_messages.thread_id and (select auth.uid()) in (t.user_a,t.user_b)
    and public.are_friends(t.user_a,t.user_b)
    and not exists(select 1 from public.blocked_users b where (b.blocker_id=t.user_a and b.blocked_id=t.user_b) or (b.blocker_id=t.user_b and b.blocked_id=t.user_a)))
);

create or replace function public.cleanup_friendship_on_block()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  delete from public.friendships where (user_a=new.blocker_id and user_b=new.blocked_id) or (user_a=new.blocked_id and user_b=new.blocker_id);
  return new;
end $$;
drop trigger if exists on_member_block_cleanup on public.blocked_users;
create trigger on_member_block_cleanup after insert on public.blocked_users for each row execute procedure public.cleanup_friendship_on_block();

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('message-media','message-media',false,52428800,array['video/mp4','video/webm','video/quicktime'])
on conflict(id) do update set public=false,file_size_limit=52428800,allowed_mime_types=excluded.allowed_mime_types;

drop policy if exists "Conversation members can view message media" on storage.objects;
create policy "Conversation members can view message media" on storage.objects for select to authenticated using (
  bucket_id='message-media'
  and (storage.foldername(name))[1] ~* '^[0-9a-f-]{36}$'
  and exists(select 1 from public.direct_threads t where t.id=((storage.foldername(name))[1])::uuid and auth.uid() in (t.user_a,t.user_b))
);
drop policy if exists "Members can upload message media" on storage.objects;
create policy "Members can upload message media" on storage.objects for insert to authenticated with check (
  bucket_id='message-media'
  and (storage.foldername(name))[1] ~* '^[0-9a-f-]{36}$'
  and (storage.foldername(name))[2]=auth.uid()::text
  and public.can_send_direct_message(((storage.foldername(name))[1])::uuid)
);
drop policy if exists "Senders can delete message media" on storage.objects;
create policy "Senders can delete message media" on storage.objects for delete to authenticated using (
  bucket_id='message-media' and (storage.foldername(name))[2]=auth.uid()::text
);

grant select,insert on public.direct_messages to authenticated;
notify pgrst, 'reload schema';



-- 0PTICBOX Network v19: full member profile layout + wallpaper modes
alter table public.profiles add column if not exists profile_handle text not null default '';
alter table public.profiles add column if not exists genre text not null default '';
alter table public.profiles add column if not exists occupation text not null default '';
alter table public.profiles add column if not exists here_for text not null default '';
alter table public.profiles add column if not exists interests text not null default '';
alter table public.profiles add column if not exists website_url text not null default '';
alter table public.profiles add column if not exists soundcloud_url text not null default '';
alter table public.profiles add column if not exists github_url text not null default '';
alter table public.profiles add column if not exists contact_email text not null default '';
alter table public.profiles add column if not exists background_mode text not null default 'cover';

alter table public.profiles drop constraint if exists profiles_profile_handle_check;
alter table public.profiles add constraint profiles_profile_handle_check check (char_length(profile_handle) <= 32);
alter table public.profiles drop constraint if exists profiles_genre_check;
alter table public.profiles add constraint profiles_genre_check check (char_length(genre) <= 100);
alter table public.profiles drop constraint if exists profiles_occupation_check;
alter table public.profiles add constraint profiles_occupation_check check (char_length(occupation) <= 120);
alter table public.profiles drop constraint if exists profiles_here_for_check;
alter table public.profiles add constraint profiles_here_for_check check (char_length(here_for) <= 180);
alter table public.profiles drop constraint if exists profiles_interests_check;
alter table public.profiles add constraint profiles_interests_check check (char_length(interests) <= 600);
alter table public.profiles drop constraint if exists profiles_website_url_check;
alter table public.profiles add constraint profiles_website_url_check check (char_length(website_url) <= 2048);
alter table public.profiles drop constraint if exists profiles_soundcloud_url_check;
alter table public.profiles add constraint profiles_soundcloud_url_check check (char_length(soundcloud_url) <= 2048);
alter table public.profiles drop constraint if exists profiles_github_url_check;
alter table public.profiles add constraint profiles_github_url_check check (char_length(github_url) <= 2048);
alter table public.profiles drop constraint if exists profiles_contact_email_check;
alter table public.profiles add constraint profiles_contact_email_check check (char_length(contact_email) <= 254);
alter table public.profiles drop constraint if exists profiles_background_mode_check;
alter table public.profiles add constraint profiles_background_mode_check check (background_mode in ('cover','contain','tile'));

notify pgrst, 'reload schema';

-- v24 shared member profile fields: same layout/features for every member
alter table public.profiles add column if not exists meet_people text not null default '';
alter table public.profiles add column if not exists instagram_embeds text not null default '';
alter table public.profiles add column if not exists youtube_embeds text not null default '';
alter table public.profiles add column if not exists featured_title text not null default '';
alter table public.profiles add column if not exists featured_kicker text not null default '';
alter table public.profiles add column if not exists featured_description text not null default '';
alter table public.profiles add column if not exists featured_url text not null default '';
alter table public.profiles add column if not exists instagram_highlight_image_url text not null default '';
alter table public.profiles add column if not exists instagram_highlight_post_url text not null default '';
alter table public.profiles drop constraint if exists profiles_meet_people_check;
alter table public.profiles add constraint profiles_meet_people_check check (char_length(meet_people) <= 1200);
alter table public.profiles drop constraint if exists profiles_instagram_embeds_check;
alter table public.profiles add constraint profiles_instagram_embeds_check check (char_length(instagram_embeds) <= 6500);
alter table public.profiles drop constraint if exists profiles_youtube_embeds_check;
alter table public.profiles add constraint profiles_youtube_embeds_check check (char_length(youtube_embeds) <= 6500);
alter table public.profiles drop constraint if exists profiles_featured_title_check;
alter table public.profiles add constraint profiles_featured_title_check check (char_length(featured_title) <= 80);
alter table public.profiles drop constraint if exists profiles_featured_kicker_check;
alter table public.profiles add constraint profiles_featured_kicker_check check (char_length(featured_kicker) <= 120);
alter table public.profiles drop constraint if exists profiles_featured_description_check;
alter table public.profiles add constraint profiles_featured_description_check check (char_length(featured_description) <= 400);
alter table public.profiles drop constraint if exists profiles_featured_url_check;
alter table public.profiles add constraint profiles_featured_url_check check (char_length(featured_url) <= 2048);
alter table public.profiles drop constraint if exists profiles_instagram_highlight_image_url_check;
alter table public.profiles add constraint profiles_instagram_highlight_image_url_check check (char_length(instagram_highlight_image_url) <= 2048);
alter table public.profiles drop constraint if exists profiles_instagram_highlight_post_url_check;
alter table public.profiles add constraint profiles_instagram_highlight_post_url_check check (char_length(instagram_highlight_post_url) <= 2048);
notify pgrst, 'reload schema';
