import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, isSupabaseConfigured } from './supabase-config.js';
let supabase=null, user=null, profile=null, posts=[], filter='all';
const $=(id)=>document.getElementById(id), warning=$('activity-config-warning'), signedOut=$('activity-signed-out'), form=$('activity-form'), sessionLabel=$('activity-session-label'), typeInput=$('activity-post-type'), feedback=$('activity-form-message'), caption=$('activity-caption'), captionCount=$('activity-caption-count'), imageInput=$('activity-image'), root=$('activity-posts'), count=$('activity-post-count'), captionLabel=$('activity-caption-label');
function say(text,error=false){feedback.textContent=text;feedback.classList.toggle('is-error',error)}
function fallbackName(value){const named=value?.user_metadata?.display_name;return(typeof named==='string'&&named.trim().length>=2?named.trim():value?.email?.split('@')[0]||'Member').slice(0,32)}
function url(value){const raw=String(value||'').trim();if(!raw)return'';try{const parsed=new URL(raw);return['http:','https:'].includes(parsed.protocol)?parsed.href:''}catch{return''}}
function youtubeId(value){const safe=url(value);if(!safe)return'';const parsed=new URL(safe);if(parsed.hostname.includes('youtu.be'))return parsed.pathname.split('/').filter(Boolean)[0]||'';if(parsed.hostname.includes('youtube.com')){if(parsed.pathname==='/watch')return parsed.searchParams.get('v')||'';const parts=parsed.pathname.split('/').filter(Boolean);if(['shorts','embed','live'].includes(parts[0]))return parts[1]||''}return''}
function platform(value){const host=new URL(value).hostname.replace(/^www\./,'').toLowerCase();if(host.includes('youtube')||host==='youtu.be')return'Open on YouTube';if(host.includes('spotify'))return'Open on Spotify';if(host.includes('soundcloud'))return'Open on SoundCloud';if(host.includes('music.apple'))return'Open in Apple Music';if(host.includes('bandcamp'))return'Open on Bandcamp';return'Open link'}
function relation(post){return Array.isArray(post.profiles)?post.profiles[0]||null:post.profiles||null}
function date(value){const d=new Date(value);return Number.isNaN(d.getTime())?'':new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'}).format(d)}
function eventDate(value){if(!value)return'';const d=new Date(`${value}T12:00:00`);return Number.isNaN(d.getTime())?'':new Intl.DateTimeFormat('en-US',{weekday:'short',month:'short',day:'numeric',year:'numeric'}).format(d)}
function avatarNode(value){const node=document.createElement('span');node.className='activity-avatar';if(value?.avatar_url){const img=document.createElement('img');img.src=value.avatar_url;img.alt='';img.loading='lazy';node.append(img)}else node.textContent=(value?.display_name||'M').slice(0,1).toUpperCase();return node}
function mediaNode(post){const uploaded=url(post.image_url), video=post.post_type==='listening'?youtubeId(post.media_url):'', source=uploaded||(video?`https://i.ytimg.com/vi/${encodeURIComponent(video)}/hqdefault.jpg`:'');const media=document.createElement('div');media.className=`activity-card-media${source?' has-image':''}`;if(source){const img=document.createElement('img');img.src=source;img.alt=post.title?`Media for ${post.title}`:'Community post image';img.loading='lazy';media.append(img)}else{const icon=document.createElement('span');icon.className='activity-media-fallback';icon.textContent=post.post_type==='event'?'✦':post.post_type==='listening'?'♫':'✎';icon.setAttribute('aria-hidden','true');media.append(icon)}return media}
function badge(type){return type==='event'?'GOING TO':type==='listening'?'NOW LISTENING':'POST'}
function render(){const shown=filter==='all'?posts:posts.filter(p=>p.post_type===filter);root.replaceChildren();count.textContent=`${shown.length} ${shown.length===1?'post':'posts'}`;if(!shown.length){const box=document.createElement('div');box.className='activity-empty';box.innerHTML='<h3>Nothing here yet.</h3><p>Make the first post above.</p>';root.append(box);return}for(const post of shown){const person=relation(post), article=document.createElement('article');article.className=`activity-card activity-card-${post.post_type}`;const identity=document.createElement('div');identity.className='activity-card-identity';const personLink=document.createElement('a');personLink.className='activity-person';personLink.href=person?.id?`profile.html?id=${encodeURIComponent(person.id)}`:'members.html';personLink.append(avatarNode(person));const idCopy=document.createElement('span'), strong=document.createElement('strong'), small=document.createElement('small');strong.textContent=person?.display_name||'Member';small.textContent=date(post.created_at);idCopy.append(strong,small);personLink.append(idCopy);const badgeEl=document.createElement('span');badgeEl.className='activity-post-badge';badgeEl.textContent=badge(post.post_type);identity.append(personLink,badgeEl);const content=document.createElement('div');content.className='activity-card-content';content.append(mediaNode(post));const copy=document.createElement('div');copy.className='activity-card-copy';if(post.title){const h=document.createElement('h2');h.textContent=post.title;copy.append(h)}if(post.post_type==='listening'&&post.subtitle){const p=document.createElement('p');p.className='activity-card-subtitle';p.textContent=`by ${post.subtitle}`;copy.append(p)}if(post.post_type==='event'){const details=document.createElement('div');details.className='activity-event-details';for(const value of [eventDate(post.event_date),post.city].filter(Boolean)){const span=document.createElement('span');span.textContent=value;details.append(span)}copy.append(details)}if(post.caption){const p=document.createElement('p');p.className='activity-card-caption';p.textContent=post.caption;copy.append(p)}const actions=document.createElement('div');actions.className='activity-card-actions';const linkUrl=url(post.media_url);if(linkUrl){const a=document.createElement('a');a.className='retro-button';a.href=linkUrl;a.target='_blank';a.rel='noopener';a.textContent=post.post_type==='event'?'Open event page':post.post_type==='listening'?platform(linkUrl):'Open link';actions.append(a)}if(user?.id===post.user_id){const remove=document.createElement('button');remove.className='retro-button danger';remove.type='button';remove.dataset.deleteActivity=String(post.id);remove.textContent='Delete my post';actions.append(remove)}if(actions.children.length)copy.append(actions);content.append(copy);article.append(identity,content);root.append(article)}}
async function ensureProfile(){const found=await supabase.from('profiles').select('id,display_name,avatar_url').eq('id',user.id).maybeSingle();if(found.error)throw found.error;if(found.data)return found.data;const made=await supabase.from('profiles').insert({id:user.id,display_name:fallbackName(user),avatar_url:''}).select('id,display_name,avatar_url').single();if(made.error)throw made.error;return made.data}
function sessionUi(){const signed=Boolean(user);signedOut.hidden=signed;form.hidden=!signed;sessionLabel.textContent=signed?`posting as ${profile?.display_name||fallbackName(user)}`:'member sign-in required'}
async function load(){const result=await supabase.from('activity_posts').select('id,user_id,post_type,title,subtitle,caption,media_url,image_url,event_date,city,visible,created_at,updated_at,profiles(id,display_name,avatar_url)').eq('visible',true).order('created_at',{ascending:false}).limit(100);if(result.error)throw result.error;posts=result.data||[];render()}
function setType(value){const next=['post','listening','event'].includes(value)?value:'post';typeInput.value=next;document.querySelectorAll('[data-post-type]').forEach(button=>{const on=button.dataset.postType===next;button.classList.toggle('is-active',on);button.setAttribute('aria-pressed',String(on))});document.querySelectorAll('[data-fields]').forEach(group=>group.hidden=group.dataset.fields!==next);captionLabel.textContent=next==='post'?'Post text':next==='listening'?'Caption (optional)':'Caption (optional)';caption.placeholder=next==='post'?'What’s on your mind?':next==='listening'?'Why is this track hitting?':'Who are you excited to see?'}
async function upload(file){if(!file)return'';if(!['image/png','image/jpeg','image/webp','image/gif'].includes(file.type))throw new Error('Use a PNG, JPG, WEBP, or GIF image.');if(file.size>5*1024*1024)throw new Error('Images must be 5 MB or smaller.');const ext=(file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'')||'jpg', path=`${user.id}/activity-${Date.now()}.${ext}`;const result=await supabase.storage.from('community-media').upload(path,file,{cacheControl:'3600',upsert:false,contentType:file.type});if(result.error)throw result.error;return supabase.storage.from('community-media').getPublicUrl(path).data.publicUrl}
async function handleSession(session){user=session?.user||null;profile=null;if(user){try{profile=await ensureProfile()}catch(error){say(error.message||'Your profile could not be loaded.',true)}}sessionUi();render()}
if(!isSupabaseConfigured()){warning.hidden=false;form.querySelectorAll('input,textarea,button').forEach(el=>el.disabled=true);root.innerHTML='<p class="review-empty">Connect Supabase and run the newest schema to turn on the community feed.</p>'}else{const{createClient}=await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.112.1/+esm');supabase=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});await handleSession((await supabase.auth.getSession()).data.session);try{await load()}catch(error){root.innerHTML='<p class="review-empty">The feed could not load. Apply the newest Supabase schema, then refresh.</p>'}supabase.auth.onAuthStateChange((_event,session)=>setTimeout(()=>handleSession(session).catch(console.warn),0))}
document.querySelectorAll('[data-post-type]').forEach(button=>button.addEventListener('click',()=>setType(button.dataset.postType)));document.querySelectorAll('[data-activity-filter]').forEach(button=>button.addEventListener('click',()=>{filter=button.dataset.activityFilter||'all';document.querySelectorAll('[data-activity-filter]').forEach(item=>{const on=item.dataset.activityFilter===filter;item.classList.toggle('is-active',on);item.setAttribute('aria-pressed',String(on))});render()}));caption?.addEventListener('input',()=>captionCount.textContent=String(caption.value.length));
form?.addEventListener('submit',async event=>{event.preventDefault();if(!supabase||!user)return;const type=['post','listening','event'].includes(typeInput.value)?typeInput.value:'post', text=caption.value.trim();let title='',subtitle='',mediaUrl='',event_date=null,city='';if(type==='post'){title=$('activity-post-title').value.trim();const raw=$('activity-post-url').value.trim();mediaUrl=raw?url(raw):'';if(raw&&!mediaUrl)return say('The link needs to start with http:// or https://.',true);if(!text&&!imageInput.files?.[0])return say('Write something or add an image.',true)}else if(type==='listening'){title=$('activity-track-title').value.trim();subtitle=$('activity-artist-name').value.trim();const raw=$('activity-media-url').value.trim();mediaUrl=raw?url(raw):'';if(!title||!subtitle)return say('Add both the track title and artist.',true);if(raw&&!mediaUrl)return say('The listening link needs to start with http:// or https://.',true)}else{title=$('activity-event-name').value.trim();event_date=$('activity-event-date').value||null;city=$('activity-event-city').value.trim();const raw=$('activity-event-url').value.trim();mediaUrl=raw?url(raw):'';if(!title||!event_date||!city)return say('Add the event name, date, and city.',true);if(raw&&!mediaUrl)return say('The event link needs to start with http:// or https://.',true)}say('Posting…');try{const image_url=await upload(imageInput.files?.[0]||null);const result=await supabase.from('activity_posts').insert({user_id:user.id,post_type:type,title,subtitle,caption:text,media_url:mediaUrl,image_url,event_date,city,visible:true,updated_at:new Date().toISOString()});if(result.error)throw result.error;form.reset();setType('post');captionCount.textContent='0';say('Posted to the community feed.');await load()}catch(error){say(error.message||'The post could not be saved.',true)}});
root?.addEventListener('click',async event=>{const button=event.target.closest('[data-delete-activity]');if(!button||!supabase||!user)return;const post=posts.find(item=>String(item.id)===button.dataset.deleteActivity);if(!post||post.user_id!==user.id)return;if(!confirm(`Delete this ${post.post_type==='post'?'post':post.post_type}?`))return;const result=await supabase.from('activity_posts').delete().eq('id',post.id).eq('user_id',user.id);if(result.error)return alert(result.error.message);await load()});setType('post');
