import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, isSupabaseConfigured } from './supabase-config.js';
const $ = (id) => document.getElementById(id);
const warning=$('messages-config-warning'), signedOut=$('messages-signed-out'), app=$('messages-app'), search=$('messages-member-search'), results=$('messages-member-results'), list=$('messages-thread-list'), count=$('messages-thread-count'), empty=$('messages-empty-state'), active=$('messages-conversation-active'), profileLink=$('messages-conversation-profile'), avatar=$('messages-conversation-avatar'), nameEl=$('messages-conversation-name'), statusEl=$('messages-conversation-status'), blockButton=$('messages-block-button'), log=$('messages-log'), form=$('messages-compose-form'), body=$('messages-body'), charCount=$('messages-character-count'), feedback=$('messages-message');
let supabase=null, user=null, selfProfile=null, profiles=[], profileMap=new Map(), threads=[], latest=new Map(), currentThread=null, otherProfile=null, blocked=false, channel=null;
function say(text,error=false){feedback.textContent=text;feedback.classList.toggle('is-error',error)}
function fallbackName(value){const named=value?.user_metadata?.display_name;return(typeof named==='string'&&named.trim().length>=2?named.trim():value?.email?.split('@')[0]||'Member').slice(0,32)}
function formatDate(value){const date=new Date(value);if(Number.isNaN(date.getTime()))return'';const same=date.toDateString()===new Date().toDateString();return new Intl.DateTimeFormat('en-US',same?{hour:'numeric',minute:'2-digit'}:{month:'short',day:'numeric'}).format(date)}
function otherId(thread){return thread.user_a===user.id?thread.user_b:thread.user_a}
function avatarNode(profile,className='messages-avatar'){const node=document.createElement('span');node.className=className;if(profile?.avatar_url){const img=document.createElement('img');img.src=profile.avatar_url;img.alt='';img.loading='lazy';node.append(img)}else node.textContent=(profile?.display_name||'M').slice(0,1).toUpperCase();return node}
async function ensureProfile(){const fields='id,display_name,avatar_url,status,profile_tagline';const found=await supabase.from('profiles').select(fields).eq('id',user.id).maybeSingle();if(found.error)throw found.error;if(found.data)return found.data;const created=await supabase.from('profiles').insert({id:user.id,display_name:fallbackName(user),avatar_url:'',status:'',profile_tagline:''}).select(fields).single();if(created.error)throw created.error;return created.data}
async function loadProfiles(){const result=await supabase.from('profiles').select('id,display_name,avatar_url,status,profile_tagline,created_at').neq('id',user.id).order('display_name').limit(250);if(result.error)throw result.error;profiles=result.data||[];profileMap=new Map(profiles.map(p=>[p.id,p]));profileMap.set(selfProfile.id,selfProfile);renderMembers()}
function renderMembers(){results.replaceChildren();const query=search.value.trim().toLowerCase();const visible=profiles.filter(p=>!query||[p.display_name,p.profile_tagline,p.status].some(v=>String(v||'').toLowerCase().includes(query))).slice(0,query?20:8);if(!visible.length){const p=document.createElement('p');p.className='review-empty';p.textContent='No members found.';results.append(p);return}for(const profile of visible){const button=document.createElement('button');button.type='button';button.className='messages-member-row';button.dataset.messageMember=profile.id;button.append(avatarNode(profile));const copy=document.createElement('span'), strong=document.createElement('strong'), small=document.createElement('small');strong.textContent=profile.display_name;small.textContent=profile.profile_tagline||profile.status||'0PTICBOX member';copy.append(strong,small);button.append(copy);results.append(button)}}
async function loadThreads(){const result=await supabase.from('direct_threads').select('id,user_a,user_b,created_at').order('created_at',{ascending:false}).limit(100);if(result.error)throw result.error;threads=result.data||[];const missing=[...new Set(threads.map(otherId))].filter(id=>!profileMap.has(id));if(missing.length){const p=await supabase.from('profiles').select('id,display_name,avatar_url,status,profile_tagline').in('id',missing);if(p.error)throw p.error;for(const row of p.data||[])profileMap.set(row.id,row)}latest=new Map();const ids=threads.map(t=>t.id);if(ids.length){const rows=await supabase.from('direct_messages').select('id,thread_id,sender_id,body,created_at').in('thread_id',ids).order('created_at',{ascending:false}).limit(500);if(rows.error)throw rows.error;for(const row of rows.data||[])if(!latest.has(row.thread_id))latest.set(row.thread_id,row)}threads.sort((a,b)=>new Date(latest.get(b.id)?.created_at||b.created_at)-new Date(latest.get(a.id)?.created_at||a.created_at));renderThreads()}
function renderThreads(){list.replaceChildren();count.textContent=`${threads.length} ${threads.length===1?'chat':'chats'}`;if(!threads.length){const p=document.createElement('p');p.className='review-empty';p.textContent='No conversations yet. Choose a member above.';list.append(p);return}for(const thread of threads){const other=profileMap.get(otherId(thread)), last=latest.get(thread.id), button=document.createElement('button');button.type='button';button.className='messages-thread-row';button.dataset.threadId=thread.id;button.classList.toggle('is-active',currentThread?.id===thread.id);button.append(avatarNode(other));const copy=document.createElement('span'), top=document.createElement('span'), strong=document.createElement('strong'), time=document.createElement('small'), preview=document.createElement('p');strong.textContent=other?.display_name||'Member';time.textContent=formatDate(last?.created_at||thread.created_at);preview.textContent=last?`${last.sender_id===user.id?'You: ':''}${last.body}`:'New conversation';top.append(strong,time);copy.append(top,preview);button.append(copy);list.append(button)}}
function header(profile){profileLink.href=`profile.html?id=${encodeURIComponent(profile.id)}`;nameEl.textContent=profile.display_name||'Member';statusEl.textContent=profile.profile_tagline||profile.status||'Private conversation';avatar.replaceChildren();if(profile.avatar_url){const img=document.createElement('img');img.src=profile.avatar_url;img.alt='';avatar.append(img)}else avatar.textContent=(profile.display_name||'M').slice(0,1).toUpperCase()}
function appendMessage(row){const article=document.createElement('article');article.className=`messages-bubble${row.sender_id===user.id?' is-mine':''}`;const p=document.createElement('p'), small=document.createElement('small');p.textContent=row.body;small.textContent=formatDate(row.created_at);article.append(p,small);log.append(article)}
async function loadMessages(){const result=await supabase.from('direct_messages').select('id,thread_id,sender_id,body,created_at').eq('thread_id',currentThread.id).order('created_at').limit(300);if(result.error)throw result.error;log.replaceChildren();for(const row of result.data||[])appendMessage(row);log.scrollTop=log.scrollHeight}
async function loadBlock(){const result=await supabase.from('blocked_users').select('blocked_id').eq('blocker_id',user.id).eq('blocked_id',otherProfile.id).maybeSingle();if(result.error)throw result.error;blocked=Boolean(result.data);blockButton.textContent=blocked?'Unblock':'Block';body.disabled=blocked;form.querySelector('button[type="submit"]').disabled=blocked;say(blocked?'You blocked this member. Unblock them to send another message.':'',blocked)}
async function subscribe(){if(channel){await supabase.removeChannel(channel);channel=null}channel=supabase.channel(`direct-${currentThread.id}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'direct_messages',filter:`thread_id=eq.${currentThread.id}`},async()=>{await loadMessages();await loadThreads()}).subscribe()}
async function openThread(id){const thread=threads.find(t=>t.id===id);if(!thread)return;currentThread=thread;otherProfile=profileMap.get(otherId(thread))||{id:otherId(thread),display_name:'Member',avatar_url:''};empty.hidden=true;active.hidden=false;header(otherProfile);renderThreads();history.replaceState({},'',`messages.html?thread=${encodeURIComponent(thread.id)}`);await Promise.all([loadMessages(),loadBlock(),subscribe()])}
async function start(other){say('Opening conversation…');const result=await supabase.rpc('start_direct_thread',{p_other_user:other});if(result.error)return say(result.error.message||'The conversation could not be opened.',true);await loadThreads();await openThread(result.data);search.value='';renderMembers()}
async function fromUrl(){const params=new URLSearchParams(location.search), withUser=params.get('with'), id=params.get('thread');if(withUser&&withUser!==user.id)return start(withUser);if(id&&threads.some(t=>t.id===id))await openThread(id)}
if(!isSupabaseConfigured()){warning.hidden=false;signedOut.hidden=false}else{const{createClient}=await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.112.1/+esm');supabase=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});user=(await supabase.auth.getSession()).data.session?.user||null;if(!user)signedOut.hidden=false;else{try{selfProfile=await ensureProfile();signedOut.hidden=true;app.hidden=false;await loadProfiles();await loadThreads();await fromUrl()}catch(error){app.hidden=false;say(error.message||'Messages could not load.',true)}}}
search?.addEventListener('input',renderMembers);results?.addEventListener('click',e=>{const b=e.target.closest('[data-message-member]');if(b&&user)start(b.dataset.messageMember)});list?.addEventListener('click',e=>{const b=e.target.closest('[data-thread-id]');if(b)openThread(b.dataset.threadId)});body?.addEventListener('input',()=>charCount.textContent=String(body.value.length));
form?.addEventListener('submit',async e=>{e.preventDefault();if(!currentThread||!user||blocked)return;const text=body.value.trim();if(!text)return say('Write a message first.',true);say('Sending…');const result=await supabase.from('direct_messages').insert({thread_id:currentThread.id,sender_id:user.id,body:text});if(result.error)return say('The message could not be sent. The conversation may be blocked or unavailable.',true);body.value='';charCount.textContent='0';say('');await loadMessages();await loadThreads()});
blockButton?.addEventListener('click',async()=>{if(!otherProfile||!user)return;if(blocked){const result=await supabase.from('blocked_users').delete().eq('blocker_id',user.id).eq('blocked_id',otherProfile.id);if(result.error)return say(result.error.message,true)}else{if(!confirm(`Block ${otherProfile.display_name}? Neither of you will be able to send new messages.`))return;const result=await supabase.from('blocked_users').insert({blocker_id:user.id,blocked_id:otherProfile.id});if(result.error)return say(result.error.message,true)}await loadBlock()});
