-- 0PTICBOX Network — community post likes and comments
-- Run this file once in Supabase > SQL Editor after uploading the v11 files.
-- Safe to run again: table, index, policy, and grant setup is idempotent.

create table if not exists public.activity_post_likes (
  post_id bigint not null references public.activity_posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (post_id, user_id)
);

create table if not exists public.activity_post_comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.activity_posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(trim(body)) between 1 and 600),
  visible boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists activity_post_likes_post_idx
  on public.activity_post_likes (post_id, created_at desc);

create index if not exists activity_post_comments_post_idx
  on public.activity_post_comments (post_id, visible, created_at);

create index if not exists activity_post_comments_user_idx
  on public.activity_post_comments (user_id, created_at desc);

alter table public.activity_post_likes enable row level security;
alter table public.activity_post_comments enable row level security;

-- Likes are public only when the parent community post is visible.
drop policy if exists "Public can read likes on visible activity posts" on public.activity_post_likes;
create policy "Public can read likes on visible activity posts"
on public.activity_post_likes for select
to anon, authenticated
using (
  exists (
    select 1
    from public.activity_posts post
    where post.id = activity_post_likes.post_id
      and post.visible = true
  )
);

drop policy if exists "Members can like visible activity posts" on public.activity_post_likes;
create policy "Members can like visible activity posts"
on public.activity_post_likes for insert
to authenticated
with check (
  user_id = (select auth.uid())
  and exists (
    select 1
    from public.activity_posts post
    where post.id = activity_post_likes.post_id
      and post.visible = true
  )
);

drop policy if exists "Members can remove their own activity likes" on public.activity_post_likes;
create policy "Members can remove their own activity likes"
on public.activity_post_likes for delete
to authenticated
using (user_id = (select auth.uid()));

-- Public visitors can read visible comments attached to visible posts.
-- Comment authors and site admins can still see a hidden comment for moderation.
drop policy if exists "Public can read visible activity comments" on public.activity_post_comments;
create policy "Public can read visible activity comments"
on public.activity_post_comments for select
to anon, authenticated
using (
  (
    visible = true
    and exists (
      select 1
      from public.activity_posts post
      where post.id = activity_post_comments.post_id
        and post.visible = true
    )
  )
  or user_id = (select auth.uid())
  or public.is_site_admin()
);

drop policy if exists "Members can comment on visible activity posts" on public.activity_post_comments;
create policy "Members can comment on visible activity posts"
on public.activity_post_comments for insert
to authenticated
with check (
  user_id = (select auth.uid())
  and visible = true
  and char_length(trim(body)) between 1 and 600
  and exists (
    select 1
    from public.activity_posts post
    where post.id = activity_post_comments.post_id
      and post.visible = true
  )
);

-- A member can delete their own comment. The post owner can remove comments
-- from their own post. Site admins can remove any comment.
drop policy if exists "Members owners or admins can delete activity comments" on public.activity_post_comments;
create policy "Members owners or admins can delete activity comments"
on public.activity_post_comments for delete
to authenticated
using (
  user_id = (select auth.uid())
  or exists (
    select 1
    from public.activity_posts post
    where post.id = activity_post_comments.post_id
      and post.user_id = (select auth.uid())
  )
  or public.is_site_admin()
);

drop policy if exists "Admins can moderate activity comments" on public.activity_post_comments;
create policy "Admins can moderate activity comments"
on public.activity_post_comments for update
to authenticated
using (public.is_site_admin())
with check (public.is_site_admin());

grant select on public.activity_post_likes to anon, authenticated;
grant insert, delete on public.activity_post_likes to authenticated;

grant select on public.activity_post_comments to anon, authenticated;
grant insert, update, delete on public.activity_post_comments to authenticated;
grant usage, select on sequence public.activity_post_comments_id_seq to authenticated;

notify pgrst, 'reload schema';
